# Greenhouse Companies Configuration
# Format: Company Name: board_name (from URL)
# Note: Addepar and Sourcegraph removed due to API unavailability
companies:
  - name: Databricks
    board_name: databricks
    url: https://job-boards.greenhouse.io/databricks
  - name: Skydio
    board_name: skydio
    url: https://job-boards.greenhouse.io/skydio
  - name: MongoDB
    board_name: mongodb
    url: https://job-boards.greenhouse.io/mongodb
  - name: Vannevar Labs
    board_name: vannevarlabs
    url: https://job-boards.greenhouse.io/vannevarlabs
  - name: Ridgeline
    board_name: ridgeline
    url: https://job-boards.greenhouse.io/ridgeline
  - name: Labelbox
    board_name: labelbox
    url: https://job-boards.greenhouse.io/labelbox
  - name: Chaos Industries
    board_name: chaosindustries
    url: https://job-boards.greenhouse.io/chaosindustries
  - name: Datavations
    board_name: datavations
    url: https://job-boards.greenhouse.io/datavations